name: MacOS

defaults:
  run:
    shell: bash

on: push

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        cxx:
          - clang++
        configs: [Release, Debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        working-directory: ${{runner.workspace}}
        run: |
          cd Cubiks/submodules/glbinding
          git apply ../../patches/0001-fix-removed-deploy-project-from-CMakeLists.txt.patch
          cd ../glm
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
          cd build
          cmake --build . --config "Release" --parallel 4
          cmake --build . --target install --config "Release"

      - name: Configure build
        working-directory: ${{runner.workspace}}
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -Bbuild -H$GITHUB_WORKSPACE \
                -DCMAKE_BUILD_TYPE=${{matrix.configs}} \
                -DCUBIKS_TESTS=ON

      - name: Build library & tests
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config "${{matrix.configs}}" --parallel 4

      - name: Run tests
        working-directory: ${{runner.workspace}}/build
        run: ./CubiksTests
